name: cio
favicon: null
layout_spectrum: 0.24290597555227578
typography_spectrum: 0.7755906966049224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.40532851801253855
  lightness: 0.6142448431346565
  saturation: 0.16719300276599824
  rhythmicContrast: 0.24422284262254834
purpose: []
